[package]
name = "discord_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
songbird = "0.4.1"
poise = "0.6.1"
dotenv = "0.15.0"